version: '3.8'

services:
  node:
    container_name: dressme-web
    tty: true
    image: node:16.19.0
    working_dir: /app
    ports:
      - ${NODE_FORWARD_PORT:-1337}:1337
    volumes:
      - .:/app
